
version: 2

models:
  - name: people
    description: "Contains Star Wars character data extracted from the swapi API"
    columns:
      - name: name
        description: "The name of the character"
        tests:
          - not_null
          - unique
      - name: height
        description: "Height of the character in centimeters"
        tests:
          - not_null
      - name: mass
        description: "Mass of the character in kilograms"
      - name: hair_color
        description: "Hair color of the character"
      - name: skin_color
        description: "Skin color of the character"
      - name: eye_color
        description: "Eye color of the character"
      - name: birth_year
        description: "Year of birth of the character"
      - name: gender
        description: "Gender of the character"